spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_info
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR-CLIENT-ID
            client-secret: YOUR-CLIENT-SECRET
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8888/Callback
            scope:
              - https://www.googleapis.com/auth/gmail.readonly
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  jpa:
    hibernate:
      ddl-auto: update
